
---

- hosts: localhost
    
 collections:
     - azure.azcollection



  vars:
    resource_group: __resourceGroupName__
    location: __location__
    webapp_name: __webappName__
    sqlserver_name: __sqlServerName__
    sqldb_name: __sqlDbName__
    admin_username: __sqlAdmin__
    admin_password: __sqlAdminSecret__

  tasks:
    - name: Create a resource group
      azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        location: "{{ location }}"
    - name: Create App Service on Windows with asp.net Runtime
      azure_rm_webapp:
        resource_group: "{{ resource_group }}"
        name: "{{ webapp_name }}"
        plan:
          resource_group: "{{ resource_group }}"
          name: myappplan
          is_linux: false
          sku: S1
          number_of_workers: 1
        app_settings:
          testkey:testvalue
        frameworks:
          - name: "net_framework"
            version: "4.8"
          
    - name: Create SQL Server
      azure_rm_sqlserver:
        resource_group: "{{ resource_group }}"
        name: "{{ sqlserver_name }}"
        location: "{{ location }}"
        version: "12.0"
        admin_username: "{{ admin_username }}"
        admin_password: "{{ admin_password }}"

    - name: Open firewall rule on azure
      azure_rm_sqlfirewallrule:
        resource_group: "{{ resource_group }}"
        server_name: "{{ sqlserver_name }}"
        startIpAddress:"166.897.83.24"
        endIpAddress: "166.897.83.24"

    - name: Create instance of SQL Database
      azure_rm_mysqldatabase:
        resource_group: "{{ resource_group }}"
        server_name: "{{ sqlserver_name }}"
        name: "{{ sqldb_name }}"
